source "https://rubygems.org"
ruby "2.0.0"

gem "middleman", "~>3.1.4"
gem "sass", "~> 3.2.10"
gem "compass"
gem "eventmachine", "1.0.0.rc.1"
gem "susy"
gem "animate-sass"
gem "slim"
gem "middleman-livereload"
